/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Battleship;

/**
 *
 * @author aamir7110
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EnemyGridA1 = new javax.swing.JLabel();
        EnemyGridB1 = new javax.swing.JLabel();
        EnemyGridC1 = new javax.swing.JLabel();
        EnemyGridD1 = new javax.swing.JLabel();
        EnemyGridE1 = new javax.swing.JLabel();
        EnemyGridD2 = new javax.swing.JLabel();
        EnemyGridE2 = new javax.swing.JLabel();
        EnemyGridA2 = new javax.swing.JLabel();
        EnemyGridB2 = new javax.swing.JLabel();
        EnemyGridC2 = new javax.swing.JLabel();
        EnemyGridD3 = new javax.swing.JLabel();
        EnemyGridE3 = new javax.swing.JLabel();
        EnemyGridA3 = new javax.swing.JLabel();
        EnemyGridB3 = new javax.swing.JLabel();
        EnemyGridC3 = new javax.swing.JLabel();
        EnemyGridD4 = new javax.swing.JLabel();
        EnemyGridE4 = new javax.swing.JLabel();
        EnemyGridA4 = new javax.swing.JLabel();
        EnemyGridB4 = new javax.swing.JLabel();
        EnemyGridC4 = new javax.swing.JLabel();
        EnemyGridD5 = new javax.swing.JLabel();
        EnemyGridE5 = new javax.swing.JLabel();
        EnemyGridA5 = new javax.swing.JLabel();
        EnemyGridB5 = new javax.swing.JLabel();
        EnemyGridC5 = new javax.swing.JLabel();
        PlayerGridA1 = new javax.swing.JLabel();
        PlayerGridB1 = new javax.swing.JLabel();
        PlayerGridC1 = new javax.swing.JLabel();
        PlayerGridD1 = new javax.swing.JLabel();
        PlayerGridE1 = new javax.swing.JLabel();
        PlayerGridE2 = new javax.swing.JLabel();
        PlayerGridA2 = new javax.swing.JLabel();
        PlayerGridB2 = new javax.swing.JLabel();
        PlayerGridC2 = new javax.swing.JLabel();
        PlayerGridD2 = new javax.swing.JLabel();
        PlayerGridE3 = new javax.swing.JLabel();
        PlayerGridA3 = new javax.swing.JLabel();
        PlayerGridB3 = new javax.swing.JLabel();
        PlayerGridC3 = new javax.swing.JLabel();
        PlayerGridD3 = new javax.swing.JLabel();
        PlayerGridE4 = new javax.swing.JLabel();
        PlayerGridA4 = new javax.swing.JLabel();
        PlayerGridB4 = new javax.swing.JLabel();
        PlayerGridC4 = new javax.swing.JLabel();
        PlayerGridD4 = new javax.swing.JLabel();
        PlayerGridE5 = new javax.swing.JLabel();
        PlayerGridA5 = new javax.swing.JLabel();
        PlayerGridB5 = new javax.swing.JLabel();
        PlayerGridC5 = new javax.swing.JLabel();
        PlayerGridD5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        EnemyGridA1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N
        EnemyGridA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnemyGridA1MouseClicked(evt);
            }
        });

        EnemyGridB1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridC1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridD1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridE1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridD2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridE2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridA2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridB2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridC2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridD3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridE3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridA3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridB3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridC3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridD4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridE4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridA4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridB4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridC4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridD5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridE5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridA5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridB5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        EnemyGridC5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridA1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N
        PlayerGridA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayerGridA1MouseClicked(evt);
            }
        });

        PlayerGridB1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N
        PlayerGridB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayerGridB1MouseClicked(evt);
            }
        });

        PlayerGridC1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N
        PlayerGridC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayerGridC1MouseClicked(evt);
            }
        });

        PlayerGridD1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridE1.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridE2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridA2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridB2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridC2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridD2.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridE3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridA3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridB3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridC3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridD3.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridE4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridA4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridB4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridC4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridD4.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridE5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridA5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridB5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridC5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        PlayerGridD5.setIcon(new javax.swing.ImageIcon("Y:\\WATERV2.png")); // NOI18N

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PlayerGridA5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridC5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridD5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridE5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PlayerGridA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlayerGridE1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EnemyGridA5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EnemyGridB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridC5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridD5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridE5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EnemyGridA4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EnemyGridB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridC4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridD4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnemyGridE4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(EnemyGridA2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EnemyGridB2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridC2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridD2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridE2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(EnemyGridA1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EnemyGridB1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridC1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridD1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnemyGridE1)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(PlayerGridA3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridB3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridC3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridD3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridE3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(PlayerGridA2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridB2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridC2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridD2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridE2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(PlayerGridA4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridB4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridC4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridD4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PlayerGridE4))))
                        .addContainerGap(325, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EnemyGridA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnemyGridB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnemyGridC3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnemyGridD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnemyGridE3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnemyGridA1)
                    .addComponent(EnemyGridB1)
                    .addComponent(EnemyGridC1)
                    .addComponent(EnemyGridD1)
                    .addComponent(EnemyGridE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnemyGridA2)
                    .addComponent(EnemyGridB2)
                    .addComponent(EnemyGridC2)
                    .addComponent(EnemyGridD2)
                    .addComponent(EnemyGridE2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EnemyGridA3)
                            .addComponent(EnemyGridB3)
                            .addComponent(EnemyGridC3)
                            .addComponent(EnemyGridD3)
                            .addComponent(EnemyGridE3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnemyGridA4)
                    .addComponent(EnemyGridB4)
                    .addComponent(EnemyGridC4)
                    .addComponent(EnemyGridD4)
                    .addComponent(EnemyGridE4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnemyGridA5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EnemyGridB5)
                        .addComponent(EnemyGridC5)
                        .addComponent(EnemyGridD5)
                        .addComponent(EnemyGridE5)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerGridA1)
                    .addComponent(PlayerGridB1)
                    .addComponent(PlayerGridC1)
                    .addComponent(PlayerGridD1)
                    .addComponent(PlayerGridE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerGridA2)
                    .addComponent(PlayerGridB2)
                    .addComponent(PlayerGridC2)
                    .addComponent(PlayerGridD2)
                    .addComponent(PlayerGridE2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerGridA3)
                    .addComponent(PlayerGridB3)
                    .addComponent(PlayerGridC3)
                    .addComponent(PlayerGridD3)
                    .addComponent(PlayerGridE3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerGridA4)
                    .addComponent(PlayerGridB4)
                    .addComponent(PlayerGridC4)
                    .addComponent(PlayerGridD4)
                    .addComponent(PlayerGridE4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerGridA5)
                    .addComponent(PlayerGridB5)
                    .addComponent(PlayerGridC5)
                    .addComponent(PlayerGridD5)
                    .addComponent(PlayerGridE5))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnemyGridA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnemyGridA1MouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_EnemyGridA1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enemy();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PlayerGridA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayerGridA1MouseClicked
        PlayerGridA1.setIcon(new javax.swing.ImageIcon("Y:\\ship.png"));
    }//GEN-LAST:event_PlayerGridA1MouseClicked

    private void PlayerGridB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayerGridB1MouseClicked
        PlayerGridB1.setIcon(new javax.swing.ImageIcon("Y:\\ship.png"));
    }//GEN-LAST:event_PlayerGridB1MouseClicked

    private void PlayerGridC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayerGridC1MouseClicked
        PlayerGridC1.setIcon(new javax.swing.ImageIcon("Y:\\ship.png"));
    }//GEN-LAST:event_PlayerGridC1MouseClicked

    public void enemy(){

        double[] enemyShips = new double[3];
        
        
        enemyShips[0]=Math.round(Math.random()* 24 + 1) ;
        enemyShips[1]= Math.round(Math.random() * 24 + 1);
        enemyShips[2]= Math.round(Math.random()* 24 + 1) ;
        
        
        
        if(enemyShips[0]== enemyShips[1]){ 
            enemyShips[0]= Math.random() * 24 + 1;
            
        }
        if(enemyShips[0]== enemyShips[2]){
            enemyShips[0]= Math.random() * 24 + 1;
        }
        if(enemyShips[1]== enemyShips[2]){
            enemyShips[1]= Math.random() * 24 + 1;
        }
        
        if(enemyShips[0]==1){

             EnemyGridA1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A1 Occupied");
        }
        else if(enemyShips[0]==2){

             EnemyGridA2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A2 Occupied");
        }
        else if(enemyShips[0]==3){

             EnemyGridA3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A3 Occupied");
        }
        else if(enemyShips[0]==4){

             EnemyGridA4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A4 Occupied");
        }
        else if(enemyShips[0]==5){

             EnemyGridA5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A5 Occupied");
        }
        else if(enemyShips[0]==6){

             EnemyGridB1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B1 Occupied");
        }
        else if(enemyShips[0]==7){

             EnemyGridB2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B2 Occupied");
        }
        else if(enemyShips[0]==8){

             EnemyGridB3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B3 Occupied");
        }
        else if(enemyShips[0]==9){

             EnemyGridB4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B4 Occupied");
        }
        else if(enemyShips[0]==10){

             EnemyGridB5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B5 Occupied");
        }
        else if(enemyShips[0]==11){

             EnemyGridC1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C1 Occupied");
        }
        else if(enemyShips[0]==12){

             EnemyGridC2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C2 Occupied");
        }
        else if(enemyShips[0]==13){

             EnemyGridC3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C3 Occupied");
        }
        else if(enemyShips[0]==14){

             EnemyGridC4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C4 Occupied");
        }
        else if(enemyShips[0]==15){

             EnemyGridC5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C5 Occupied");
        }
        else if(enemyShips[0]==16){

             EnemyGridD1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D1 Occupied");
        }
        else if(enemyShips[0]==17){

             EnemyGridD2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D2 Occupied");
        }
        else if(enemyShips[0]==18){

             EnemyGridD3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D3 Occupied");
        }
        else if(enemyShips[0]==19){

             EnemyGridD4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D4 Occupied");
        }
        else if(enemyShips[0]==20){

             EnemyGridD5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D5 Occupied");
        }
        else if(enemyShips[0]==21){

             EnemyGridE1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E1 Occupied");
        }
        else if(enemyShips[0]==22){

             EnemyGridE2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E2 Occupied");
        }
        else if(enemyShips[0]==23){

             EnemyGridE3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E3 Occupied");
        }
        else if(enemyShips[0]==24){

             EnemyGridE4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E4 Occupied");
        }
        else if(enemyShips[0]==25){

             EnemyGridE5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E5 Occupied");
        }
        if(enemyShips[1]==1){

             EnemyGridA1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A1 Occupied");
        }
        else if(enemyShips[1]==2){

             EnemyGridA2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A2 Occupied");
        }
        else if(enemyShips[1]==3){

             EnemyGridA3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A3 Occupied");
        }
        else if(enemyShips[1]==4){

             EnemyGridA4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A4 Occupied");
        }
        else if(enemyShips[1]==5){

             EnemyGridA5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A5 Occupied");
        }
        else if(enemyShips[1]==6){

             EnemyGridB1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B1 Occupied");
        }
        else if(enemyShips[1]==7){

             EnemyGridB2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B2 Occupied");
        }
        else if(enemyShips[1]==8){

             EnemyGridB3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B3 Occupied");
        }
        else if(enemyShips[1]==9){

             EnemyGridB4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B4 Occupied");
        }
        else if(enemyShips[1]==10){

             EnemyGridB5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B5 Occupied");
        }
        else if(enemyShips[1]==11){

             EnemyGridC1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C1 Occupied");
        }
        else if(enemyShips[1]==12){

             EnemyGridC2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C2 Occupied");
        }
        else if(enemyShips[1]==13){

             EnemyGridC3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C3 Occupied");
        }
        else if(enemyShips[1]==14){

             EnemyGridC4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C4 Occupied");
        }
        else if(enemyShips[1]==15){

             EnemyGridC5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C5 Occupied");
        }
        else if(enemyShips[1]==16){

             EnemyGridD1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D1 Occupied");
        }
        else if(enemyShips[1]==17){

             EnemyGridD2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D2 Occupied");
        }
        else if(enemyShips[1]==18){

             EnemyGridD3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D3 Occupied");
        }
        else if(enemyShips[1]==19){

             EnemyGridD4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D4 Occupied");
        }
        else if(enemyShips[1]==20){

             EnemyGridD5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D5 Occupied");
        }
        else if(enemyShips[1]==21){

             EnemyGridE1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E1 Occupied");
        }
        else if(enemyShips[1]==22){

             EnemyGridE2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E2 Occupied");
        }
        else if(enemyShips[1]==23){

             EnemyGridE3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E3 Occupied");
        }
        else if(enemyShips[1]==24){

             EnemyGridE4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E4 Occupied");
        }
        else if(enemyShips[1]==25){

             EnemyGridE5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E5 Occupied");
        }
        
        if(enemyShips[2]==1){

             EnemyGridA1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A1 Occupied");
        }
        else if(enemyShips[2]==2){

             EnemyGridA2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A2 Occupied");
        }
        else if(enemyShips[2]==3){

             EnemyGridA3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A3 Occupied");
        }
        else if(enemyShips[2]==4){

             EnemyGridA4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A4 Occupied");
        }
        else if(enemyShips[2]==5){

             EnemyGridA5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid A5 Occupied");
        }
        else if(enemyShips[2]==6){

             EnemyGridB1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B1 Occupied");
        }
        else if(enemyShips[2]==7){

             EnemyGridB2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B2 Occupied");
        }
        else if(enemyShips[2]==8){

             EnemyGridB3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B3 Occupied");
        }
        else if(enemyShips[2]==9){

             EnemyGridB4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B4 Occupied");
        }
        else if(enemyShips[2]==10){

             EnemyGridB5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid B5 Occupied");
        }
        else if(enemyShips[2]==11){

             EnemyGridC1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C1 Occupied");
        }
        else if(enemyShips[2]==12){

             EnemyGridC2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C2 Occupied");
        }
        else if(enemyShips[2]==13){

             EnemyGridC3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C3 Occupied");
        }
        else if(enemyShips[2]==14){

             EnemyGridC4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C4 Occupied");
        }
        else if(enemyShips[2]==15){

             EnemyGridC5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid C5 Occupied");
        }
        else if(enemyShips[2]==16){

             EnemyGridD1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D1 Occupied");
        }
        else if(enemyShips[2]==17){

             EnemyGridD2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D2 Occupied");
        }
        else if(enemyShips[2]==18){

             EnemyGridD3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D3 Occupied");
        }
        else if(enemyShips[2]==19){

             EnemyGridD4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D4 Occupied");
        }
        else if(enemyShips[2]==20){

             EnemyGridD5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid D5 Occupied");
        }
        else if(enemyShips[2]==21){

             EnemyGridE1.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E1 Occupied");
        }
        else if(enemyShips[2]==22){

             EnemyGridE2.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E2 Occupied");
        }
        else if(enemyShips[2]==23){

             EnemyGridE3.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E3 Occupied");
        }
        else if(enemyShips[2]==24){

             EnemyGridE4.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E4 Occupied");
        }
        else if(enemyShips[2]==25){

             EnemyGridE5.setIcon(new javax.swing.ImageIcon("Y:\\Grid Occupied.png"));
             System.out.println("Grid E5 Occupied");
        }
        
    }
    
    
    public void player(){
    
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnemyGridA1;
    private javax.swing.JLabel EnemyGridA2;
    private javax.swing.JLabel EnemyGridA3;
    private javax.swing.JLabel EnemyGridA4;
    private javax.swing.JLabel EnemyGridA5;
    private javax.swing.JLabel EnemyGridB1;
    private javax.swing.JLabel EnemyGridB2;
    private javax.swing.JLabel EnemyGridB3;
    private javax.swing.JLabel EnemyGridB4;
    private javax.swing.JLabel EnemyGridB5;
    private javax.swing.JLabel EnemyGridC1;
    private javax.swing.JLabel EnemyGridC2;
    private javax.swing.JLabel EnemyGridC3;
    private javax.swing.JLabel EnemyGridC4;
    private javax.swing.JLabel EnemyGridC5;
    private javax.swing.JLabel EnemyGridD1;
    private javax.swing.JLabel EnemyGridD2;
    private javax.swing.JLabel EnemyGridD3;
    private javax.swing.JLabel EnemyGridD4;
    private javax.swing.JLabel EnemyGridD5;
    private javax.swing.JLabel EnemyGridE1;
    private javax.swing.JLabel EnemyGridE2;
    private javax.swing.JLabel EnemyGridE3;
    private javax.swing.JLabel EnemyGridE4;
    private javax.swing.JLabel EnemyGridE5;
    private javax.swing.JLabel PlayerGridA1;
    private javax.swing.JLabel PlayerGridA2;
    private javax.swing.JLabel PlayerGridA3;
    private javax.swing.JLabel PlayerGridA4;
    private javax.swing.JLabel PlayerGridA5;
    private javax.swing.JLabel PlayerGridB1;
    private javax.swing.JLabel PlayerGridB2;
    private javax.swing.JLabel PlayerGridB3;
    private javax.swing.JLabel PlayerGridB4;
    private javax.swing.JLabel PlayerGridB5;
    private javax.swing.JLabel PlayerGridC1;
    private javax.swing.JLabel PlayerGridC2;
    private javax.swing.JLabel PlayerGridC3;
    private javax.swing.JLabel PlayerGridC4;
    private javax.swing.JLabel PlayerGridC5;
    private javax.swing.JLabel PlayerGridD1;
    private javax.swing.JLabel PlayerGridD2;
    private javax.swing.JLabel PlayerGridD3;
    private javax.swing.JLabel PlayerGridD4;
    private javax.swing.JLabel PlayerGridD5;
    private javax.swing.JLabel PlayerGridE1;
    private javax.swing.JLabel PlayerGridE2;
    private javax.swing.JLabel PlayerGridE3;
    private javax.swing.JLabel PlayerGridE4;
    private javax.swing.JLabel PlayerGridE5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
